linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - typecheck
    - misspell
    - unparam
    - unused
    - gosec
    - gocritic
    - revive
    - nilerr
    - bodyclose
    - goconst
    - prealloc
    - exhaustive
    - noctx

run:
  timeout: 5m
  tests: true

linters-settings:
  goconst:
    min-occurrences: 4

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - goconst
