#!/bin/sh
# Post a Discord release announcement using the release_notes.md artifact.
#
# Required environment variables:
#   DISCORD_RELEASE_WEBHOOK_URL — Discord webhook URL (masked CI variable)
#   CI_COMMIT_TAG               — Git tag (e.g., v1.7.0)
#   CI_PROJECT_URL              — GitHub project URL
#
# Required file:
#   release_notes.md            — Generated by the changelog CI job
set -eu

RELEASE_URL="${CI_PROJECT_URL}/releases/tag/${CI_COMMIT_TAG}"
CHANGELOG_URL="${CI_PROJECT_URL}/blob/main/CHANGELOG.md"
MAX_LINES=25

# ── Firefly/Serenity quotes with character attribution ──
# One is selected at random for each release notification.
# Uses a heredoc so apostrophes are preserved naturally.
QUOTES=$(cat <<'ENDQUOTES'
"I aim to misbehave." — Mal
"Shiny. Let's be bad guys." — Jayne
"We're still flying. That's not much. It's enough." — Mal
"You can't take the sky from me." — Theme Song
"Big damn heroes, sir." — Zoe
"I swear by my pretty floral bonnet, I will end you." — Mal
"Also, I can kill you with my brain." — River
"Curse your sudden but inevitable betrayal!" — Wash
"If you can't do something smart, do something right." — Shepherd Book
"No power in the 'verse can stop me." — River
"We're gonna explode? I don't wanna explode." — Wash
"I am a leaf on the wind. Watch how I soar." — Wash
"Everything's shiny, Captain. Not to fret." — Kaylee
"My days of not taking you seriously are certainly coming to a middle." — Mal
"Oh god, oh god, we're all gonna die." — Wash
"I don't believe there's a power in the 'verse that can stop Kaylee from being cheerful." — Kaylee
"This is my very favorite gun." — Jayne
"You know what the first rule of flying is? Love." — Mal
"I believe that woman is planning to shoot me again." — Mal
"The human body can be drained of blood in 8.6 seconds given adequate vacuuming systems." — River
"I can hurt you." — Simon
"This must be what going mad feels like." — Simon
"One of you is going to fall and die, and I'm not cleaning it up." — Simon
"I never back down from a fight." — Zoe
"Every well-bred petty crook knows the small concealable weapons always go to the far left of the place setting." — Inara
"What did I say to you about barging into my shuttle?" — Inara
"Mal, if you die, I will kill you." — Inara
ENDQUOTES
)
QUOTE=$(printf '%s\n' "$QUOTES" | grep -v '^$' | shuf -n 1)

# ── Transform release notes for Discord markdown ──
#   - Convert [**breaking**] tags to emoji
#   - Strip commit hash links: ([abc1234](https://...)) → removed
#   - Convert scope italics: *(scope)* → **scope:**
#   - Convert ### headers → **bold**
#   - Convert - bullets → • bullets
NOTES=$(sed \
  -e 's/ \[\*\*breaking\*\*\]/ ⚠️ **BREAKING**/g' \
  -e 's/ (\[[a-f0-9]*\]([^)]*))//g' \
  -e 's/\*(\([^)]*\))\*/**\1:**/g' \
  -e 's/^### \(.*\)/**\1**/g' \
  -e 's/^- /• /' \
  release_notes.md)

# ── Truncate on a line boundary; append link if truncated ──
TOTAL=$(printf '%s\n' "$NOTES" | wc -l)
if [ "$TOTAL" -gt "$MAX_LINES" ]; then
  NOTES="$(printf '%s\n' "$NOTES" | head -n "$MAX_LINES")

*… [see full release notes](${RELEASE_URL})*"
fi

# ── Build footer links ──
LINKS="📄 [Release Notes](${RELEASE_URL}) • 📋 [Full Changelog](${CHANGELOG_URL})"

# ── Build and send Discord webhook payload ──
jq -n \
  --arg title "${CI_COMMIT_TAG} Released" \
  --arg desc "$NOTES" \
  --arg url "$RELEASE_URL" \
  --arg links "$LINKS" \
  --arg quote "$QUOTE" \
  '{embeds: [{
    author: {name: "⚡ Capacitarr", url: "https://capacitarr.app"},
    title: $title,
    url: $url,
    description: $desc,
    color: 5814783,
    fields: [
      {name: "\u200b", value: $links, inline: false},
      {name: "🔥 From the Cortex", value: $quote, inline: false}
    ]
  }]}' \
| curl -sf -H "Content-Type: application/json" -d @- "$DISCORD_RELEASE_WEBHOOK_URL"
